### ISSUE TITLE
enhancement request : use a header bar / Application menu

### ISSUE THREAD

**Issue by pyluyten** [Jiehong/Zhudi#4]
Do you like header bar applications?

For example, 
- Application menu can be used to offer "About" & "Settings".
- Header bar / Or application menu can be used to switch from "Dictionary" to "Segmentation".

**Comment by Jiehong** [comment]
I thought about it at first, but then I realised that I only have 2 things: "about" and "settings".

Plus, I want to keep the design as simple as possible, and I'm not happy about the way the settings work currently, nor the way to change "From Chinese" "To Chinese". I'm thinking about replacing it with 1 single icon which would act as a toggle (with some sort of animation) containing a picture maybe…

Therefore, I'm not really for a header bar containing almost nothing.

For the application menu for switching between Dictionary and Segmentation, that's an idea. But, right now, each function is 1 click away, while the application menu would make it 2 clicks away. If I had dozens of functions, I would say that an application menu would be a great idea, but right now, maybe not.

So, I will try to improve things for About and settings, but I am happy with the tab layout for the 2 main functions as for now.

Unless you convince me of a kick-ass idea ;)

**Comment by pyluyten** [comment]
> "But, right now, each function is 1 click away,"

Ok sure.

> (...) "From Chinese" "To Chinese". I'm thinking about replacing it with 1 single icon which would act as a toggle (with some sort of animation) containing a picture maybe…

I could imagine a button with a label "From Chinese", clicking on it switches and changes the button label to "To Chinese". Would it be ok?

**Comment by Jiehong** [comment]
Yes, the button idea is good. I'll see to it soon.

**Comment by Jiehong** [comment]
I've tried a design in the new dictionary_design branch. Here is a screenshot of the change:

![new_button](https://cloud.githubusercontent.com/assets/1061229/7441214/cf4a31e6-f0dd-11e4-8501-27ab1ae859c6.png)

What do you think about it?

**Comment by pyluyten** [comment]
thanks for the work!, sorry I should have offer to try.

Plus, I realize now there is some issue
- 中>X might not be understood
- "From Chinese" / "To Chinese" might be a bit long. I'm not sure about 从中 (is that proper Chinese? If so, would user get it?)
- There would be locale abbrev (en / cn / .. eg "en > 中") but I'm not sure every user knows this.

Sorry not to have imagined this before, but maybe scanning input for a-z - as opposed to any Chinese input - could tell Zhudi which way to translate? or could this break some cases, like Japanese>Chinese?

**Comment by Jiehong** [comment]
In Chinese, it's more "中转英" (Chinese transformed to English"). In this particular case, we don't use 从.
But I'm afraid people wouldn't get it (and the second part is needed, which means detecting what is the target language), depending on their level, and I want to avoid that.

And yes, I tried to shorten it, because the button would be too large.

The auto-detection would probably break in Japanese or Korean (since some characters are in the Chinese-Japanese-Korean part of UTF-8, which is a common set of shared characters).

This would also break for entries composed of figures (is 5 Chinese or not? haha).

But:
- I don't think people would look for numbers only;
- I don't know about a Japanese/Korean version of CC-EDICT.

On the other hand, if it doesn't work well, I could still offer a line saying: "the input has been assumed to be in Chinese." followed by a button which would re-launch the search in the other language maybe.
But I would only do that if there are actual issues with the auto-detection.

I'll think about how to implement that correctly on the same branch.

**Comment by Jiehong** [comment]
So, I've implemented this function in the same branch, mainly by detecting all possible Chinese characters (in the Unicode Pane).

Therefore, I'm now sure it won't be a problem for any language not using Chinese (but Greek, Russian or French would virtually never fail for example).

It seems to be working extremely well, so you may want to give it a try.

Here is a screenshot of the current state:
![auto_detect](https://cloud.githubusercontent.com/assets/1061229/7442757/b9f09056-f11e-11e4-96b7-c20ed6febbf2.png)

**Comment by pyluyten** [comment]
yup, at least in my case, this is very pleasant to use. It allows to perform searches in different direction without changing anything

**Comment by Jiehong** [comment]
I consider this to be fixed. I've opened #5 for the option button.
